### PR TITLE
Add support for global preferences and csslint/jshint options

### PR DESCRIPTION
**Pull request by Lichtjaeger**
Hi,
I've added support for preference file like I did for your csslint and jshint extensions.
This extension now also looking for the other preferences and ._rc-files, so it checks style and script tags the same way as css and js files.

### CODE REVIEW

**Comment by cfjedimaster** [comment]
I'm confused - are you saying it adds support for csslint and jshint?

**Comment by Lichtjaeger** [comment]
No. HTMLHint has native options to use csslint and jshint. In your other extensions you require both to the global namespace, so we can use them if the extensions are installed.

With my changes the htmlhint-extension is looking in the `brackets.json` for jshint and csslint options and uses them as defaults. In addition it's now looking for `.jshintrc` and `.csslintrc` files and uses there options as well.

I have tested it on my Windows machine and it works well.

**Comment by cfjedimaster** [comment]
Hmm. So far it isn't working for me at all. Debugging.

**Comment by cfjedimaster** [comment]
Did you test when no custom rules were supplied? No .htmlhintrc?

**Comment by cfjedimaster** [comment]
Yeah, that's the issue. If you have no rules, it should use a default, but it is returning nothing.

**Comment by cfjedimaster** [comment]
So, by default, this is what your passing to HTMLHinter in my current dir which has *no* rc files:

{"jshint":{"undef":true,"predef":[]},"csslint":{"order-alphabetical":false}}

In preferences, I did have the CSSlint setting. I don't have a .jshintrc in the current folder though.

So yeah - not sure what to say here. Obviously you want to pass these prefs to the lib, but when you don't pass an empty object and have no rules for HTMLHint, it breaks and reports nothing.

**Comment by cfjedimaster** [comment]
FYI, I filed an issue over on HTMLHint for this too: https://github.com/yaniswang/HTMLHint/issues/106

In the end though - I think I need to revert this PR, right?

**Comment by Lichtjaeger** [comment]
I can confirm your results. Sorry, I don't tested if the default rules of HTMLhint works in this scenario.

Looks as if they don't merge their defaults object with the ruleset. They override it. (Same for CSSlint (Don't testet JSHint)).

I've opened a new PR(#10) with the solution.

**Comment by cfjedimaster** [comment]
It happens. ;)

On Sat, Jan 16, 2016 at 4:04 AM, Peter Scheler <notifications@github.com>
wrote:

> I can confirm your results. Sorry, I don't tested if the default rules of
> HTMLhint works in this scenario.
>
> Looks as if they don't merge their defaults object with the ruleset. They
> override it. (Same for CSSlint (Don't testet JSHint)).
>
> I've opened a new PR(#10
> <https://github.com/cfjedimaster/brackets-htmlhint/pull/10>) with the
> solution.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-htmlhint/pull/9#issuecomment-172178737>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Pull request merged**
